services:

  database:
    image: postgres:15-alpine3.18
    container_name: database
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d managerpassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - data_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '127.0.0.1:5432:5432'
    restart: always

volumes:
  data_db:
